name = "WallE"
uuid = "409c7e06-86dc-11e9-30a5-6d15a9183e58"
authors = ["CodeLenz <eduardobarplenz@gmail.com>"]
repo-url = "https://github.com/CodeLenz/WallE.git"
deps = ["LinearAlgebra"]
version = "0.1.0"
